trigger:
- main   

pool:
  vmImage: ubuntu-latest


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true


- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: "Install Python dependencies"

- script: |
    python sales_data_pipeline.py
  displayName: "Run sales data pipeline"

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'output'
    ArtifactName: 'sales-data'
    publishLocation: 'Container'
