
trigger:

schedules:
  - cron: "0 3 * * 1"   
    branches:
      include:
        - main
    always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    persistCredentials: true

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: "Install Python dependencies"

  - script: |
      python report_generator.py
    displayName: "Generate Attendance & Task KPIs"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'reports'
      ArtifactName: 'AttendanceReport'
      publishLocation: 'Container'
    displayName: "Publish Reports Artifact"
