trigger:
  branches:
    include:
      - main

schedules:
  - cron: "0 6 * * 1"   
    displayName: "Weekly Sales Analysis"
    branches:
      include:
        - main
    always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    persistCredentials: true

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: "Install Python dependencies"

  - script: |
      python sales_analysis.py
    displayName: "Run Sales ETL & Analysis"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'output'
      ArtifactName: 'SalesReport'
      publishLocation: 'Container'
    displayName: "Publish Sales Report Artifact"

  - script: |
      python log_lowest_stores.py
    displayName: "Log Lowest Performing Stores"
